#!/usr/bin/env python3
"""HCA renal cortex 训练策略消融实验一键编排脚本（单 seed）。

三种训练策略（严格消融标准，仅 seed=0，耗时控制）：

  1. aug_pt   : test 增强预训练（train+test 合并的单模态数据预训练）+ 联合训练 (pair_pretrain)
  2. scratch  : 无预训练，直接使用 train 数据集做匹配训练 (pair_scratch)
  3. train_pt : 仅使用 train 单模态数据预训练 + 联合训练 (pair_pretrain)

联合训练超参数（参考 outputs/hca_renal_cortex_dropout_01/config.yaml，继承不改）:
  train_steps=6000, eval_points=200, save_points=500
  optimizer: lr=2e-4, warmup=500, steady_1=500, cosine_anneal=5000, min_lr=5e-5
  model.dropout_p=0.1（继承 config）
  loss: clip_weight=20, temperature=0.15, bottom_k_ratio=0.15, weight_bottom=5.0（继承 config）

单组学预训练超参数（参考 case_renal_cortex_pretrain_pair.yaml，任务规定统一）:
  每模态 lr=1e-3, train_steps=4000, warmup=400, steady_1=0, cosine=3600, min_lr=1e-4
  batch_size=256, vae_beta=1.0, eval_points=200, save_points=4000（仅最终 ckpt）

用法::

    conda activate snapatac
    python scripts/run_hca_renal_cortex_strategy_ablation.py                        # 全量
    python scripts/run_hca_renal_cortex_strategy_ablation.py --strategies scratch   # 单策略
    nohup python -u scripts/run_hca_renal_cortex_strategy_ablation.py > logs/hca_renal_cortex_strategy_ablation.out 2>&1 &

断点续跑: 每个实验幂等——已有完整评估结果/预训练 ckpt 自动跳过。
"""

from __future__ import annotations

import argparse
import gc
import glob
import json
import os
import random
import re
import shutil
import subprocess
import sys
import time
import traceback
from datetime import datetime
from pathlib import Path

import yaml

# ============ 路径配置 ============
ROOT = Path("/home/rsun@ZHANGroup.local/solid_recover_main")
CONFIGS_DIR = ROOT / "configs"
OUTPUTS_DIR = ROOT / "outputs"
REPORTS_DIR = ROOT / "exp-reports" / "hca_renal_cortex_strategy_ablation"
PREPARED_DIR = OUTPUTS_DIR / "hca_renal_cortex_strategy_ablation" / "prepared"
PRETRAIN_BASE = OUTPUTS_DIR / "hca_renal_cortex_strategy_ablation" / "pretrain"
PAIR_BASE = OUTPUTS_DIR / "hca_renal_cortex_strategy_ablation" / "pair"

# 联合训练参考配置（继承其 training/optimizer/loss/model 设置）
BASE_CONFIG = OUTPUTS_DIR / "hca_renal_cortex_dropout_01" / "config.yaml"
TRAIN_H5MU = str(ROOT / "paper_figure" / "hca_renal_cortex" / "train.h5mu")
TEST_H5MU = str(ROOT / "paper_figure" / "hca_renal_cortex" / "test.h5mu")
KEY_1 = "rna_count"
KEY_2 = "peak_count"

STRATEGIES = ["aug_pt", "scratch", "train_pt"]
DEFAULT_SEEDS = [0]  # 单 seed（实验耗时久，用户规定）

# 单组学预训练超参数（参考 case_renal_cortex_pretrain_pair.yaml: lr=1e-3, 4000 步, batch=256）
PRETRAIN_LR = 1e-3
PRETRAIN_STEPS = 4000
PRETRAIN_WARMUP = 400
PRETRAIN_STEADY_1 = 0
PRETRAIN_COSINE = 3600
PRETRAIN_MIN_LR = 1e-4
PRETRAIN_EVAL_POINTS = 200
PRETRAIN_SAVE_POINTS = 4000
PRETRAIN_BATCH_SIZE = 256
PRETRAIN_VAE_BETA = 1.0


# ============ 基础工具 ============

def log(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def header(msg: str) -> None:
    bar = "=" * 70
    print(f"\n{bar}\n[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {msg}\n{bar}\n", flush=True)


def set_seed(seed: int) -> None:
    """设置全局随机种子（python/numpy/torch/cuda），保证训练可复现。"""
    random.seed(seed)
    import numpy as np
    import torch

    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def resolve_to_gpu(flag: str, device: str) -> bool:
    """解析 --to-gpu 参数：yes/no 强制指定，auto 按可用显存自动判断。

    hca_renal_cortex 联合训练全量数据上 GPU 约需 17.5GB（train+test 两个模态 dense float32），
    单组学预训练 atac 约 15.3GB；阈值取可用显存 >= 24GB 时启用。
    """
    import torch

    if flag == "no":
        return False
    if flag == "yes":
        return True
    # auto
    if device != "cuda" or not torch.cuda.is_available():
        return False
    free_mib = torch.cuda.mem_get_info()[0] / (1024 ** 2)
    total_mib = torch.cuda.get_device_properties(0).total_memory / (1024 ** 2)
    log(f"GPU 显存: 总 {total_mib/1024:.0f}GB / 空闲 {free_mib/1024:.1f}GB")
    if free_mib >= 24 * 1024:
        log("显存充足，启用 to_gpu（训练数据全量加载到 GPU）")
        return True
    log("显存不足，自动回退到 CPU 数据加载（逐 batch 传输）")
    return False


def load_yaml(path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def write_yaml(data: dict, path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# Auto-generated by run_hca_renal_cortex_strategy_ablation.py\n")
        f.write(f"# {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def find_final_ckpt(models_dir: str):
    """在 ``models_dir`` 下找 step 号最大的 ``ckpt_*.pth``。"""
    ckpts = glob.glob(os.path.join(models_dir, "ckpt_*.pth"))
    if not ckpts:
        return None

    def _step(p: str) -> int:
        m = re.search(r"ckpt_(\d+)\.pth", os.path.basename(p))
        return int(m.group(1)) if m else 0

    return sorted(ckpts, key=_step)[-1]


# ============ 步骤 1: 数据准备 ============

def prepare_data() -> dict:
    """探查 train/test 单模态数据并缓存 4 个 AnnData 到磁盘（幂等）。

    返回 {rna_combined, atac_combined, rna_train, atac_train} 的 h5ad 路径 dict。
    """
    header("步骤 1/5: 数据准备（探查 + 单模态缓存）")
    import anndata as ad
    import muon as mu

    paths = {
        "rna_combined": PREPARED_DIR / "rna_combined.h5ad",
        "atac_combined": PREPARED_DIR / "atac_combined.h5ad",
        "rna_train": PREPARED_DIR / "rna_train.h5ad",
        "atac_train": PREPARED_DIR / "atac_train.h5ad",
    }
    expected_vars = {KEY_1: 14577, KEY_2: 101123}
    missing = [p for p in paths.values() if not p.exists()]
    if not missing:
        log("单模态缓存已存在，跳过生成；校验特征数 ...")
        for name, p in paths.items():
            a = ad.read_h5ad(p)
            expect = expected_vars[KEY_1 if name.startswith("rna") else KEY_2]
            ok = a.n_vars == expect
            log(f"  {name}: {a.shape} (expect vars={expect}, {'OK' if ok else 'MISMATCH'})")
            if not ok:
                missing.append(p)
        if not missing:
            return paths

    PREPARED_DIR.mkdir(parents=True, exist_ok=True)
    log(f"加载 train: {TRAIN_H5MU}")
    mdata_tr = mu.read_h5mu(TRAIN_H5MU)
    log(f"加载 test:  {TEST_H5MU}")
    mdata_te = mu.read_h5mu(TEST_H5MU)

    # 探查 var 一致性；若 test 多出 train 没有的 var 则报错，否则对齐到 train 顺序
    for key in (KEY_1, KEY_2):
        v1, v2 = mdata_tr[key].var_names, mdata_te[key].var_names
        same = (v1 == v2).all()
        log(f"{key}: train={mdata_tr[key].shape} test={mdata_te[key].shape} var 一致={same}")
        if not same:
            extra = set(v2) - set(v1)
            if extra:
                raise RuntimeError(f"{key}: test 含 train 没有的 var 共 {len(extra)} 个，无法对齐")
            mdata_te[key] = mdata_te[key][:, v1]

    log("生成单模态缓存:")
    for name, src, mod in [
        ("rna_combined", "both", KEY_1),
        ("atac_combined", "both", KEY_2),
        ("rna_train", "train", KEY_1),
        ("atac_train", "train", KEY_2),
    ]:
        adata_tr = mdata_tr[mod]
        adata_te = mdata_te[mod] if src == "both" else None
        if adata_te is not None:
            adata = ad.concat([adata_tr, adata_te], join="outer")
        else:
            adata = adata_tr.copy()
        expect = expected_vars[mod]
        assert adata.n_vars == expect, f"{name} n_vars={adata.n_vars} != {expect}"
        adata.write_h5ad(paths[name])
        log(f"  {name}: {adata.shape} -> {paths[name]}")

    return paths


# ============ 步骤 2: 单组学预训练 ============

def run_pretrain_omic(adata, feature_num, hidden_params, embed_dim, out_dir, device, seed, tag, to_gpu=False) -> str:
    """运行单组学 VAE 预训练（4000 步，lr=1e-3，batch=256，仅保存最终 ckpt），返回 ckpt 路径。

    adata 可为 AnnData 对象或 h5ad 文件路径（str/Path，自动读取）。
    """
    from solid_recover.models.single import SinglePretrain

    if isinstance(adata, (str, os.PathLike)):
        import scanpy as sc

        log(f"[{tag}] 读取单模态 h5ad: {adata}")
        adata = sc.read_h5ad(str(adata))

    out_dir = Path(out_dir)
    models_dir = out_dir / "models"
    existing = find_final_ckpt(str(models_dir)) if models_dir.exists() else None
    if existing:
        log(f"[{tag}] 已有预训练 ckpt，跳过: {existing}")
        return existing
    if out_dir.exists():
        log(f"[{tag}] 清理不完整预训练残留: {out_dir}")
        shutil.rmtree(out_dir)

    t0 = time.time()
    set_seed(seed)
    model = SinglePretrain(
        feature_num=feature_num,
        hidden_params=hidden_params,
        embed_dim=embed_dim,
        use_rmsnorm=True,
        use_residual=True,
        dropout_p=0.0,
    )
    train_ds, test_ds = model.create_dataset(adata, test_size=0.05, random_state=42)
    del adata  # 释放 AnnData（tensor 已由 SingleDataset 持有）
    gc.collect()
    model.setup_data(train_ds, test_ds, batch_size=PRETRAIN_BATCH_SIZE)
    if to_gpu:
        train_ds.to_gpu()
        test_ds.to_gpu()
    model.set_loss(beta=PRETRAIN_VAE_BETA)
    model.configure_optimizer(
        lr=PRETRAIN_LR,
        warmup_steps=PRETRAIN_WARMUP,
        steady_1_steps=PRETRAIN_STEADY_1,
        cosine_anneal_steps=PRETRAIN_COSINE,
        min_lr=PRETRAIN_MIN_LR,
    )
    model.set_project(str(out_dir))
    log(
        f"[{tag}] 预训练: feature_num={feature_num} hidden={hidden_params} embed={embed_dim} "
        f"steps={PRETRAIN_STEPS} lr={PRETRAIN_LR} batch={PRETRAIN_BATCH_SIZE} seed={seed} "
        f"to_gpu={to_gpu}"
    )
    model.train(
        train_steps=PRETRAIN_STEPS,
        eval_points=PRETRAIN_EVAL_POINTS,
        save_points=PRETRAIN_SAVE_POINTS,
        device=device,
    )
    ckpt = find_final_ckpt(os.path.join(model.project_dir, "models"))
    if not ckpt:
        raise RuntimeError(f"[{tag}] 预训练未产出 checkpoint: {out_dir}")
    log(f"[{tag}] 预训练完成 ({time.time()-t0:.0f}s): {ckpt}")
    del train_ds, test_ds, model
    gc.collect()
    return ckpt


# ============ 步骤 3: 联合训练 ============

def run_pair_experiment(strategy: str, seed: int, device: str, prepared: dict, to_gpu: bool = False):
    """执行一个 (策略, seed) 实验：预训练(如需) -> 联合训练 -> 评估。

    返回指标 dict 或 None（失败时返回 None，由 main 记录）。
    """
    tag = f"{strategy}_seed{seed}"
    pair_dir = PAIR_BASE / tag
    cfg_path = CONFIGS_DIR / f"hca_renal_cortex_{tag}.yaml"

    # ---- 状态检查（幂等）----
    status = check_pair_status(pair_dir)
    if status == "done":
        log(f"[{tag}] 已有完整评估结果，跳过训练与评估")
        return extract_best_metrics(pair_dir, strategy, seed)
    log(f"[{tag}] 实验状态: {status}")

    base = load_yaml(BASE_CONFIG)
    model_cfg = base["model"]

    # ---- 预训练（aug_pt / train_pt 策略）----
    rna_ckpt = atac_ckpt = None
    if strategy in ("aug_pt", "train_pt"):
        header(f"步骤 2/5: 单组学预训练 ({tag})")
        if strategy == "aug_pt":
            rna_adata, atac_adata = prepared["rna_combined"], prepared["atac_combined"]
        else:
            rna_adata, atac_adata = prepared["rna_train"], prepared["atac_train"]
        pretrain_base = PRETRAIN_BASE / tag
        rna_ckpt = run_pretrain_omic(
            rna_adata,
            feature_num=model_cfg["feature_num_1"],
            hidden_params=list(model_cfg["hidden_params_1"]),
            embed_dim=model_cfg["embed_dim"],
            out_dir=pretrain_base / "rna_pretrain",
            device=device,
            seed=seed,
            tag=f"{tag}/rna",
            to_gpu=to_gpu,
        )
        atac_ckpt = run_pretrain_omic(
            atac_adata,
            feature_num=model_cfg["feature_num_2"],
            hidden_params=list(model_cfg["hidden_params_2"]),
            embed_dim=model_cfg["embed_dim"],
            out_dir=pretrain_base / "atac_pretrain",
            device=device,
            seed=seed,
            tag=f"{tag}/atac",
            to_gpu=to_gpu,
        )

    # ---- 生成联合训练配置（继承参考 config，仅覆盖 task/project_dir/device/ckpt）----
    cfg = dict(base)
    cfg["task"] = "pair_pretrain" if strategy in ("aug_pt", "train_pt") else "pair_scratch"
    cfg["training"] = dict(base["training"])
    cfg["training"]["project_dir"] = str(pair_dir)
    cfg["training"]["device"] = device
    if strategy in ("aug_pt", "train_pt"):
        cfg["ckpt"] = {"omic_1": rna_ckpt, "omic_2": atac_ckpt}
    else:
        cfg.pop("ckpt", None)  # scratch 不加载任何预训练权重（严格消融标准）
    write_yaml(cfg, cfg_path)

    # ---- 联合训练 ----
    if status != "trained":
        if pair_dir.exists():
            log(f"[{tag}] 清理不完整训练残留: {pair_dir}")
            shutil.rmtree(pair_dir)
        header(f"步骤 3/5: 联合训练 ({tag})")
        train_pair(cfg, cfg_path, device, seed, tag, to_gpu=to_gpu)

    # ---- 评估 ----
    actual_dir = find_pair_actual_dir(pair_dir)
    if not actual_dir:
        raise RuntimeError(f"[{tag}] 找不到联合训练输出目录: {pair_dir}")
    if not os.path.exists(os.path.join(actual_dir, "eval_result", "metrics_summary.json")):
        header(f"步骤 4/5: 评估 ({tag})")
        run_eval(actual_dir, tag)
    return extract_best_metrics(actual_dir, strategy, seed)


def check_pair_status(pair_dir: Path) -> str:
    """返回实验目录状态: 'done' 已评估 / 'trained' 已训练未评估 / 'clean' 无产物。"""
    if os.path.exists(os.path.join(pair_dir, "eval_result", "metrics_summary.json")):
        return "done"
    models_dir = pair_dir / "models"
    if models_dir.is_dir() and glob.glob(str(models_dir / "ckpt_*.pth")):
        return "trained"
    return "clean"


def find_pair_actual_dir(pair_dir: Path):
    """定位实际输出目录（兼容 Trainer 追加时间戳后缀的情况）。"""
    if os.path.isfile(os.path.join(pair_dir, "config.yaml")):
        return str(pair_dir)
    parent = pair_dir.parent
    prefix = pair_dir.name
    if parent.is_dir():
        candidates = [
            os.path.join(parent, n)
            for n in os.listdir(parent)
            if n.startswith(prefix) and os.path.isfile(os.path.join(parent, n, "config.yaml"))
        ]
        if candidates:
            return max(candidates, key=os.path.getmtime)
    return None


def train_pair(cfg: dict, cfg_path, device: str, seed: int, tag: str, to_gpu: bool = False) -> None:
    """使用库 API 执行联合训练（不经 CLI，保证全局 seed 生效）。"""
    from solid_recover.data.prepare import prepare_pair_data
    from solid_recover.models.pair import PairPretrain, PairScratch

    t0 = time.time()
    set_seed(seed)
    train_ds, test_ds = prepare_pair_data(TRAIN_H5MU, TEST_H5MU, KEY_1, KEY_2, to_gpu=to_gpu)

    m = cfg["model"]
    feat_1 = train_ds[0]["omic_1"].shape[0]
    feat_2 = train_ds[0]["omic_2"].shape[0]
    assert feat_1 == m["feature_num_1"], f"feature_num_1 mismatch: {feat_1} vs {m['feature_num_1']}"
    assert feat_2 == m["feature_num_2"], f"feature_num_2 mismatch: {feat_2} vs {m['feature_num_2']}"

    cls = PairPretrain if cfg["task"] == "pair_pretrain" else PairScratch
    model = cls(
        feature_num_1=feat_1,
        feature_num_2=feat_2,
        hidden_params_1=list(m["hidden_params_1"]),
        hidden_params_2=list(m["hidden_params_2"]),
        embed_dim=m["embed_dim"],
        use_rmsnorm=m.get("use_rmsnorm", True),
        use_residual=m.get("use_residual", True),
        dropout_p=m.get("dropout_p", 0.1),
    )
    if isinstance(model, PairPretrain):
        model.load_pretrained(omic_1_ckpt=cfg["ckpt"]["omic_1"], omic_2_ckpt=cfg["ckpt"]["omic_2"])

    model.setup_data(train_ds, test_ds, batch_size=cfg["data"]["batch_size"])

    loss = cfg["loss"]
    model.set_loss(
        vae_beta_1=loss.get("vae_beta_1", 1.0),
        vae_beta_2=loss.get("vae_beta_2", 1.0),
        clip_weight=float(loss.get("clip_weight", 1.0)),
        cross_recon_1=float(loss.get("cross_recon_1", 0.2)),
        cross_recon_2=float(loss.get("cross_recon_2", 0.2)),
        temperature=float(loss.get("temperature", 0.07)),
        use_weight=loss.get("use_weight", False),
        top_k_ratio=loss.get("top_k_ratio", 0.1),
        bottom_k_ratio=loss.get("bottom_k_ratio", 0.1),
        weight_top=loss.get("weight_top", 0.1),
        weight_bottom=loss.get("weight_bottom", 2.0),
    )

    opt = cfg["optimizer"]
    model.configure_optimizer(
        lr=float(opt["lr"]),
        warmup_steps=opt["warmup_steps"],
        steady_1_steps=opt["steady_1_steps"],
        cosine_anneal_steps=opt["cosine_anneal_steps"],
        min_lr=float(opt["min_lr"]),
    )
    model.set_project(cfg["training"]["project_dir"])
    tr = cfg["training"]
    log(
        f"[{tag}] 联合训练: task={cfg['task']} steps={tr['train_steps']} "
        f"save={tr['save_points']} eval={tr['eval_points']} "
        f"lr={opt['lr']} batch={cfg['data']['batch_size']} seed={seed} to_gpu={to_gpu}"
    )
    model.train(
        train_steps=tr["train_steps"],
        eval_points=tr["eval_points"],
        save_points=tr["save_points"],
        device=device,
        config_copy_path=str(cfg_path),
    )
    log(f"[{tag}] 联合训练完成 ({time.time()-t0:.0f}s): {model.project_dir}")
    del train_ds, test_ds, model
    gc.collect()


# ============ 步骤 4: 评估 ============

def run_eval(actual_dir: str, tag: str) -> None:
    """调用 scripts/eval.sh 评估输出目录下的所有 checkpoint。"""
    cmd = f"bash scripts/eval.sh {actual_dir} cuda"
    log(f"[{tag}] 执行: {cmd}")
    r = subprocess.run(cmd, shell=True, cwd=str(ROOT), capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"[{tag}] 评估失败 exit={r.returncode}: {r.stderr[-800:]}")
    if not os.path.exists(os.path.join(actual_dir, "eval_result", "metrics_summary.json")):
        raise RuntimeError(f"[{tag}] 评估未产出 metrics_summary.json")
    log(f"[{tag}] 评估完成")


def extract_best_metrics(pair_dir: str, strategy: str, seed: int) -> dict:
    """从 metrics_summary.json 提取 best-step 的 top_1/foscttm/top_5。"""
    mj = os.path.join(pair_dir, "eval_result", "metrics_summary.json")
    with open(mj, "r", encoding="utf-8") as f:
        data = json.load(f)
    t1 = data["metrics"]["top_1_hit"]["values"]
    steps = data["metrics"]["top_1_hit"]["steps"]
    best_idx = max(range(len(t1)), key=lambda i: t1[i])
    res = {
        "strategy": strategy,
        "seed": seed,
        "best_step": steps[best_idx],
        "top_1": t1[best_idx],
        "foscttm": data["metrics"]["foscttm"]["values"][best_idx],
        "top_5": data["metrics"]["top_5_hit"]["values"][best_idx],
        "output_dir": pair_dir,
    }
    log(
        f"[{strategy}_seed{seed}] best_step={res['best_step']} "
        f"top_1={res['top_1']:.6f} foscttm={res['foscttm']:.6f} top_5={res['top_5']:.6f}"
    )
    return res


# ============ 步骤 5: 汇总报告 ============

def generate_report(results: list) -> None:
    header("步骤 5/5: 汇总报告")
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    # CSV
    import csv

    csv_path = REPORTS_DIR / "results.csv"
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f, fieldnames=["strategy", "seed", "best_step", "top_1", "foscttm", "top_5", "output_dir"]
        )
        w.writeheader()
        w.writerows(results)
    log(f"CSV -> {csv_path}")

    # Markdown
    lines = [
        "# HCA renal cortex 训练策略消融实验汇总",
        "",
        f"生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 实验设置",
        "",
        "| 策略 | 说明 | 联合训练任务 |",
        "|------|------|-------------|",
        "| aug_pt | test 增强预训练（train+test 单模态）+ 联合训练 | pair_pretrain |",
        "| scratch | 无预训练，直接联合训练 | pair_scratch |",
        "| train_pt | 仅 train 单模态预训练 + 联合训练 | pair_pretrain |",
        "",
        "联合训练（继承 outputs/hca_renal_cortex_dropout_01/config.yaml）: "
        "train_steps=6000, save_points=500, eval_points=200, "
        "lr=2e-4, warmup=500, steady_1=500, cosine_anneal=5000, min_lr=5e-5",
        "",
        "单组学预训练（参考 case_renal_cortex_pretrain_pair.yaml）: "
        "lr=1e-3, train_steps=4000, warmup=400, steady_1=0, cosine=3600, min_lr=1e-4, "
        "batch_size=256, vae_beta=1.0（仅保存最终 ckpt）",
        "",
        "## 各实验明细",
        "",
        "| 策略 | seed | best_step | top_1 | foscttm | top_5 |",
        "|------|-----:|----------:|------:|--------:|------:|",
    ]
    for r in sorted(results, key=lambda x: (x["strategy"], x["seed"])):
        lines.append(
            f"| {r['strategy']} | {r['seed']} | {r['best_step']} | "
            f"{r['top_1']:.6f} | {r['foscttm']:.6f} | {r['top_5']:.6f} |"
        )

    lines += ["", "## 策略对比", "", "| 策略 | top_1 | foscttm | top_5 |"]
    import statistics

    for strategy in STRATEGIES:
        rs = [r for r in results if r["strategy"] == strategy]
        if not rs:
            lines.append(f"| {strategy} | N/A | N/A | N/A |")
            continue
        lines.append(f"| {strategy} | {rs[0]['top_1']:.6f} | {rs[0]['foscttm']:.6f} | {rs[0]['top_5']:.6f} |")

    # 最优策略判定（按 top_1）
    valid = [s for s in STRATEGIES if any(r["strategy"] == s for r in results)]
    if valid:
        best_s = max(valid, key=lambda s: statistics.mean([r["top_1"] for r in results if r["strategy"] == s]))
        lines += [
            "",
            "## 结论",
            "",
            f"按 top_1，最优策略: **{best_s}** "
            f"({statistics.mean([r['top_1'] for r in results if r['strategy'] == best_s]):.6f})",
            "",
        ]

    md_path = REPORTS_DIR / "summary.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    log(f"MD -> {md_path}")


# ============ main ============

def main() -> int:
    parser = argparse.ArgumentParser(description="HCA renal cortex 训练策略消融实验编排脚本")
    parser.add_argument("--strategies", default=",".join(STRATEGIES), help="逗号分隔策略列表")
    parser.add_argument("--seeds", default=",".join(map(str, DEFAULT_SEEDS)), help="逗号分隔 seed 列表")
    parser.add_argument("--device", default="cuda", help="训练设备 (default: cuda)")
    parser.add_argument("--to-gpu", default="auto", choices=["auto", "yes", "no"],
                        help="训练数据全量加载到 GPU: auto(按显存自动)/yes/no (default: auto)")
    parser.add_argument("--skip-data", action="store_true", help="跳过数据准备步骤")
    args = parser.parse_args()

    strategies = [s.strip() for s in args.strategies.split(",") if s.strip()]
    seeds = [int(s) for s in args.seeds.split(",") if s.strip()]
    invalid = [s for s in strategies if s not in STRATEGIES]
    if invalid:
        log(f"错误: 未知策略 {invalid}，可选: {STRATEGIES}")
        return 1
    log(f"策略: {strategies} | seeds: {seeds} | device: {args.device}")

    # 环境检查
    import torch

    if args.device == "cuda" and not torch.cuda.is_available():
        log("错误: cuda 不可用")
        return 1
    log(f"torch={torch.__version__} cuda={torch.cuda.is_available()}")

    to_gpu = resolve_to_gpu(args.to_gpu, args.device)
    t_start = time.time()
    try:
        prepared = None if args.skip_data else prepare_data()
        results = []
        for strategy in strategies:
            for seed in seeds:
                t0 = time.time()
                try:
                    r = run_pair_experiment(strategy, seed, args.device, prepared, to_gpu=to_gpu)
                    if r:
                        results.append(r)
                except Exception as e:
                    log(f"[{strategy}_seed{seed}] 实验失败: {e}")
                    traceback.print_exc()
                log(f"[{strategy}_seed{seed}] 耗时 {time.time()-t0:.0f}s")
        generate_report(results)
    except KeyboardInterrupt:
        log("用户中断")
        return 130
    except Exception as e:
        log(f"异常终止: {e}")
        traceback.print_exc()
        return 1

    log(f"全部完成，总耗时 {(time.time()-t_start)/3600:.1f} 小时")
    return 0


if __name__ == "__main__":
    sys.exit(main())
