#!/usr/bin/env python3
"""
HCA Renal Cortex 消融实验自动编排脚本
========================================
按顺序执行 Phase 1~8，每阶段训练→评估→提取最优参数→生成configs→汇总报告→Git提交

用法: 
  conda activate snapatac
  python scripts/run_ablation.py

或后台运行:
  nohup python -u scripts/run_ablation.py > logs/ablation_full.out 2>&1 &
"""

import os
import sys
import json
import shutil
import subprocess
import time
import datetime
import copy
from pathlib import Path

import yaml

# ============ 路径配置 ============
ROOT = Path("/home/rsun@ZHANGroup.local/solid_recover_main")
CONFIGS_DIR = ROOT / "configs"
OUTPUTS_DIR = ROOT / "outputs"
EXP_REPORTS_DIR = ROOT / "exp-reports"
LOGS_DIR = ROOT / "logs"
TRAIN_SCRIPT = ROOT / "scripts" / "train.sh"
EVAL_SCRIPT = ROOT / "scripts" / "eval.sh"
CONDA_SH = "/home/rsun@ZHANGroup.local/anaconda3/etc/profile.d/conda.sh"

# ============ 基线配置（从 t040 复制核心参数） ============
def base_config():
    return {
        "task": "pair_pretrain",
        "data": {
            "train_data_path": str(ROOT / "paper_figure/hca_renal_cortex/train.h5mu"),
            "test_data_path": str(ROOT / "paper_figure/hca_renal_cortex/test.h5mu"),
            "key_1": "rna_count",
            "key_2": "peak_count",
            "batch_size": 512,
            "to_gpu": True,
        },
        "model": {
            "feature_num_1": 14577,
            "feature_num_2": 101123,
            "hidden_params_1": [1024, 256],
            "hidden_params_2": [1024, 256],
            "embed_dim": 64,
            "use_rmsnorm": True,
            "use_residual": True,
            "dropout_p": 0.0,
        },
        "training": {
            "train_steps": 6000,
            "eval_points": 200,
            "save_points": 500,
            "device": "cuda",
        },
        "optimizer": {
            "lr": 2e-4,
            "warmup_steps": 500,
            "steady_1_steps": 500,
            "cosine_anneal_steps": 5000,
            "min_lr": 5e-5,
        },
        "loss": {
            "vae_beta_1": 1.0,
            "vae_beta_2": 1.0,
            "clip_weight": 20.0,
            "cross_recon_1": 0.75,
            "cross_recon_2": 0.75,
            "temperature": 0.30,
            "use_weight": True,
            "top_k_ratio": 0.1,
            "bottom_k_ratio": 0.02,
            "weight_top": 0.1,
            "weight_bottom": 5.0,
        },
        "ckpt": {
            "omic_1": str(ROOT / "outputs/hca_renal_cortex_pretrain_pair_v2/rna_pretrain/models/ckpt_4000.pth"),
            "omic_2": str(ROOT / "outputs/hca_renal_cortex_pretrain_pair_v2/atac_pretrain/models/ckpt_4000.pth"),
        },
    }


# ============ 跨阶段最优参数 ============
class State:
    """全局状态，跨阶段传递最优参数"""
    def __init__(self):
        self.best_temperature = None
        self.best_bottom_k_ratio = None
        self.best_weight_top = None
        self.best_weight_bottom = None
        self.best_embed_dim = None
        self.best_hidden_params = None
        self.best_pretrain_steps = None
        self.best_clip_weight = None
        self.best_cross_recon = None
        self.best_batch_size = None
        self.all_results = {}  # phase_name -> list of experiment dicts

state = State()


# ============ 工具函数 ============

def log(msg):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {msg}", flush=True)


def write_yaml(config, filepath):
    """用 PyYAML 写配置文件"""
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, 'w') as f:
        f.write(f"# Auto-generated by run_ablation.py\n")
        f.write(f"# {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    log(f"  📝 配置: {filepath}")


def run_cmd(cmd, log_file=None, timeout=None):
    """执行shell命令，返回 exit_code。如果指定 log_file，则输出写入该文件"""
    log(f"  🔧 {cmd[:120]}{'...' if len(cmd) > 120 else ''}")
    if log_file:
        with open(log_file, 'a') as lf:
            lf.write(f"\n[{datetime.datetime.now()}] CMD: {cmd}\n")
            result = subprocess.run(
                cmd, shell=True, cwd=ROOT, executable='/bin/bash',
                stdout=lf, stderr=subprocess.STDOUT,
                timeout=timeout,
            )
    else:
        result = subprocess.run(
            cmd, shell=True, cwd=ROOT, executable='/bin/bash',
            capture_output=True, text=True,
            timeout=timeout,
        )
    ok = result.returncode == 0
    if not ok:
        stderr_info = ''
        if not log_file and result.stderr:
            stderr_info = f' stderr={result.stderr[-200:]}'
        log(f"  ❌ 失败, exit_code={result.returncode}{stderr_info}")
    return ok


def find_actual_output_dir(project_dir_name):
    """查找实际输出目录（可能有时间戳后缀）"""
    actual = OUTPUTS_DIR / project_dir_name
    if actual.exists():
        return actual
    matches = sorted(OUTPUTS_DIR.glob(f"{project_dir_name}*"))
    if matches:
        actual = matches[-1]
        log(f"  📁 找到带时间戳目录: {actual.name}")
        return actual
    return None


def extract_metrics(project_dir_name):
    """从 metrics_summary.json 提取所有指标"""
    actual = find_actual_output_dir(project_dir_name)
    if not actual:
        log(f"  ❌ 输出目录不存在: {project_dir_name}")
        return None
    mp = actual / "eval_result" / "metrics_summary.json"
    if not mp.exists():
        log(f"  ❌ metrics_summary.json 不存在: {mp}")
        return None
    with open(mp) as f:
        return json.load(f)


def find_best(data):
    """找 top_1_hit 最优的 step"""
    top1 = data['metrics']['top_1_hit']
    vals = top1['values']
    best_idx = max(range(len(vals)), key=lambda i: vals[i])
    return {
        'best_step': top1['steps'][best_idx],
        'top_1': vals[best_idx],
        'foscttm': data['metrics']['foscttm']['values'][best_idx],
        'top_5': data['metrics']['top_5_hit']['values'][best_idx],
    }


def compare_tie(t1_a, fos_a, t1_b, fos_b):
    """比较：先看 top_1；差距<0.0005 则 foscttm 低者胜"""
    if abs(t1_a - t1_b) < 0.0005:
        return fos_a < fos_b
    return t1_a > t1_b


def copy_metrics(project_dir_name, phase_dir, exp_name):
    """复制 metrics_summary.json 到 exp-reports"""
    actual = find_actual_output_dir(project_dir_name)
    if not actual:
        return
    src = actual / "eval_result" / "metrics_summary.json"
    dst_dir = EXP_REPORTS_DIR / phase_dir / exp_name
    dst_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst_dir / "metrics_summary.json")
    # 复制 TB 日志（如果有）
    tb_dir = actual / "logs"
    if tb_dir.exists():
        tb_dst = dst_dir / "tb_logs"
        if not tb_dst.exists():
            shutil.copytree(tb_dir, tb_dst)
    log(f"  📋 归档 → {dst_dir}")


def generate_summary_md(phase_name, experiments, best_id, phase_dir):
    """生成阶段汇总 summary.md"""
    lines = [
        f"# {phase_name}",
        "",
        f"生成时间: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 排名汇总",
        "",
        "| 排名 | 实验 | best_step | top_1 | foscttm | top_5 |",
        "|-----:|------|----------:|------:|--------:|------:|",
    ]
    sorted_exps = sorted(experiments, key=lambda x: x['top_1'], reverse=True)
    for rank, exp in enumerate(sorted_exps, 1):
        marker = " **← 最优**" if exp['id'] == best_id else ""
        lines.append(f"| {rank} | {exp['id']} | {exp['best_step']} | {exp['top_1']:.6f} | {exp['foscttm']:.6f} | {exp['top_5']:.6f} |{marker}")
    
    lines.append("")
    for exp in experiments:
        lines.append(f"## {exp['id']} 逐步轨迹")
        lines.append("")
        lines.append("| step | top_1 | foscttm |")
        lines.append("|-----:|------:|--------:|")
        for i, s in enumerate(exp['steps']):
            b = "**" if s == exp['best_step'] else ""
            lines.append(f"| {b}{s}{b} | {exp['top_1_list'][i]:.6f} | {exp['foscttm_list'][i]:.6f} |")
        lines.append("")
    
    best_exp = next(e for e in experiments if e['id'] == best_id)
    lines.append("## 结论")
    lines.append(f"最优: **{best_id}**, top_1={best_exp['top_1']:.6f}, foscttm={best_exp['foscttm']:.6f}")
    lines.append("")
    
    content = '\n'.join(lines)
    sp = EXP_REPORTS_DIR / phase_dir / "summary.md"
    sp.parent.mkdir(parents=True, exist_ok=True)
    with open(sp, 'w') as f:
        f.write(content)
    log(f"  📊 summary → {sp}")
    return content


def git_commit_push(phase_dir, commit_msg):
    """提交到 exp-reports 分支"""
    log(f"  🔄 Git 提交...")
    
    # 获取当前分支
    r = subprocess.run("git rev-parse --abbrev-ref HEAD", shell=True, cwd=ROOT, capture_output=True, text=True)
    cur = r.stdout.strip()
    
    # stash 未提交更改
    r = subprocess.run("git diff --quiet && git diff --cached --quiet", shell=True, cwd=ROOT)
    stashed = False
    if r.returncode != 0:
        subprocess.run("git stash", shell=True, cwd=ROOT, capture_output=True)
        stashed = True
    
    try:
        subprocess.run("git checkout exp-reports", shell=True, cwd=ROOT, capture_output=True)
        subprocess.run(f"git add exp-reports/{phase_dir}/", shell=True, cwd=ROOT, capture_output=True)
        subprocess.run(f'git commit -m "{commit_msg}"', shell=True, cwd=ROOT, capture_output=True)
        r = subprocess.run("git push origin exp-reports", shell=True, cwd=ROOT, capture_output=True, text=True)
        if r.returncode == 0:
            log(f"  ✅ Push 成功")
        else:
            log(f"  ⚠️ Push: {r.stderr[-200:]}")
    finally:
        subprocess.run(f"git checkout {cur}", shell=True, cwd=ROOT, capture_output=True)
        if stashed:
            subprocess.run("git stash pop", shell=True, cwd=ROOT, capture_output=True)


# ============ 单实验执行 ============

def run_experiment(config_name, project_dir, exp_id, phase_dir):
    """训练→评估→提取指标→归档，返回结果dict或None"""
    log(f"\n{'='*60}")
    log(f"  🧪 {exp_id} | config={config_name} | output={project_dir}")
    log(f"{'='*60}")
    
    config_path = CONFIGS_DIR / f"{config_name}.yaml"
    if not config_path.exists():
        log(f"  ❌ 配置不存在: {config_path}")
        return None
    
    # 检查是否已有评估结果，有则跳过
    existing_data = extract_metrics(project_dir)
    if existing_data is not None:
        best = find_best(existing_data)
        log(f"  ⏭️ 已有结果，跳过训练。best_step={best['best_step']}, top_1={best['top_1']:.6f}")
        copy_metrics(project_dir, phase_dir, exp_id)
        return {
            'id': exp_id,
            'config_name': config_name,
            'project_dir': project_dir,
            'best_step': best['best_step'],
            'top_1': best['top_1'],
            'foscttm': best['foscttm'],
            'top_5': best['top_5'],
            'steps': existing_data['metrics']['top_1_hit']['steps'],
            'top_1_list': existing_data['metrics']['top_1_hit']['values'],
            'foscttm_list': existing_data['metrics']['foscttm']['values'],
        }
    
    retries = 3
    for attempt in range(retries):
        log(f"  [训练] 尝试 {attempt+1}/{retries}...")
        t0 = time.time()
        cmd = f"source {CONDA_SH} && conda activate snapatac && bash scripts/train.sh {config_path} cuda"
        ok = run_cmd(cmd, log_file=LOGS_DIR / f"ablation_train_{config_name}.out")
        t1 = time.time()
        if ok:
            log(f"  ✅ 训练完成 ({t1-t0:.0f}s)")
            break
        log(f"  ⚠️ 训练失败，{'' if attempt == retries-1 else '重试中...'}")
        if attempt == retries - 1:
            log(f"  ❌ 训练失败，跳过此实验")
            return None
    
    # 查找实际输出目录
    actual_dir = find_actual_output_dir(project_dir)
    if not actual_dir:
        log(f"  ❌ 找不到输出目录")
        return None
    actual_name = actual_dir.name
    
    # 评估
    log(f"  [评估] ...")
    cmd = f"source {CONDA_SH} && conda activate snapatac && bash scripts/eval.sh {actual_dir} cuda"
    ok = run_cmd(cmd, log_file=LOGS_DIR / f"ablation_eval_{config_name}.out")
    if not ok:
        log(f"  ❌ 评估失败")
        return None
    log(f"  ✅ 评估完成")
    
    # 提取指标
    data = extract_metrics(actual_name)
    if data is None:
        return None
    
    best = find_best(data)
    result = {
        'id': exp_id,
        'config_name': config_name,
        'project_dir': project_dir,
        'best_step': best['best_step'],
        'top_1': best['top_1'],
        'foscttm': best['foscttm'],
        'top_5': best['top_5'],
        'steps': data['metrics']['top_1_hit']['steps'],
        'top_1_list': data['metrics']['top_1_hit']['values'],
        'foscttm_list': data['metrics']['foscttm']['values'],
    }
    
    log(f"  📊 best_step={best['best_step']}, top_1={best['top_1']:.6f}, foscttm={best['foscttm']:.6f}")
    
    # 归档
    copy_metrics(actual_name, phase_dir, exp_id)
    
    return result


def find_best_experiment(results):
    """从结果列表中找最优（top_1优先，ties用foscttm）"""
    best = max(results, key=lambda x: x['top_1'])
    for r in results:
        if r['id'] != best['id']:
            if not compare_tie(best['top_1'], best['foscttm'], r['top_1'], r['foscttm']):
                best = r
    return best


# ============ 已有温度结果加载 ============

def load_existing_temperature():
    existing = []
    temp_map = {tid: tval for tid, tval in [
        ('t007', 0.07), ('t010', 0.10), ('t012', 0.12),
        ('t015', 0.15), ('t020', 0.20), ('t030', 0.30),
    ]}
    for tid, tval in temp_map.items():
        data = extract_metrics(f"hca_renal_cortex_pretrain_{tid}")
        if data:
            best = find_best(data)
            existing.append({
                'id': tid,
                'config_name': f'hca_renal_cortex_pretrain_{tid}',
                'project_dir': f'outputs/hca_renal_cortex_pretrain_{tid}',
                'best_step': best['best_step'],
                'top_1': best['top_1'],
                'foscttm': best['foscttm'],
                'top_5': best['top_5'],
                'steps': data['metrics']['top_1_hit']['steps'],
                'top_1_list': data['metrics']['top_1_hit']['values'],
                'foscttm_list': data['metrics']['foscttm']['values'],
            })
            log(f"  📂 已有: {tid} (t={tval}), top_1={best['top_1']:.6f}")
    return existing


# ============ Phase 实现 ============

def phase1_temperature():
    log(f"\n{'#'*70}")
    log(f"#  Phase 1: Temperature 扩展扫描")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_temperature_sweep"
    
    # 加载已有结果
    all_r = load_existing_temperature()
    
    # 执行新实验
    new_exps = [
        ("hca_renal_cortex_pretrain_t040", "hca_renal_cortex_pretrain_t040", "t040"),
        ("hca_renal_cortex_pretrain_t050", "hca_renal_cortex_pretrain_t050", "t050"),
        ("hca_renal_cortex_pretrain_t070", "hca_renal_cortex_pretrain_t070", "t070"),
        ("hca_renal_cortex_pretrain_t100", "hca_renal_cortex_pretrain_t100", "t100"),
    ]
    
    for cn, pd, eid in new_exps:
        r = run_experiment(cn, pd, eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        log("❌ Phase 1 无有效结果")
        return None
    
    best = find_best_experiment(all_r)
    temp_map = {'t007':0.07,'t010':0.10,'t012':0.12,'t015':0.15,'t020':0.20,
                't030':0.30,'t040':0.40,'t050':0.50,'t070':0.70,'t100':1.00}
    state.best_temperature = temp_map.get(best['id'], 0.30)
    
    log(f"\n🏆 T_best = {state.best_temperature}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 1: Temperature 扫描", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase1: T_best={state.best_temperature}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase1'] = all_r
    return best


def phase2_bottom_k():
    log(f"\n{'#'*70}")
    log(f"#  Phase 2: bottom_k_ratio 扫描")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_bottom_k_sweep"
    
    bk_pairs = [
        ("bk001", 0.01), ("bk002", 0.02), ("bk005", 0.05),
        ("bk010", 0.10), ("bk015", 0.15), ("bk020", 0.20),
    ]
    
    all_r = []
    for eid, bk in bk_pairs:
        cfg = copy.deepcopy(base_config())
        cfg['loss']['temperature'] = state.best_temperature
        cfg['loss']['bottom_k_ratio'] = bk
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        return None
    
    best = find_best_experiment(all_r)
    bk_map = dict(bk_pairs)
    state.best_bottom_k_ratio = bk_map.get(best['id'], 0.02)
    
    log(f"\n🏆 bottom_k_ratio = {state.best_bottom_k_ratio}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 2: bottom_k_ratio 扫描", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase2: bk={state.best_bottom_k_ratio}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase2'] = all_r
    return best


def phase3_weight_top():
    log(f"\n{'#'*70}")
    log(f"#  Phase 3: weight_top 扫描")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_weight_top_sweep"
    
    wt_pairs = [("wt001", 0.01), ("wt005", 0.05), ("wt010", 0.10)]
    
    all_r = []
    for eid, wt in wt_pairs:
        cfg = copy.deepcopy(base_config())
        cfg['loss']['temperature'] = state.best_temperature
        cfg['loss']['bottom_k_ratio'] = state.best_bottom_k_ratio
        cfg['loss']['weight_top'] = wt
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        return None
    
    best = find_best_experiment(all_r)
    wt_map = dict(wt_pairs)
    state.best_weight_top = wt_map.get(best['id'], 0.1)
    
    log(f"\n🏆 weight_top = {state.best_weight_top}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 3: weight_top 扫描", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase3: wt={state.best_weight_top}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase3'] = all_r
    return best


def phase4_weight_bottom():
    log(f"\n{'#'*70}")
    log(f"#  Phase 4: weight_bottom 扫描")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_weight_bottom_sweep"
    
    wb_pairs = [("wb2", 2.0), ("wb5", 5.0), ("wb10", 10.0)]
    
    all_r = []
    for eid, wb in wb_pairs:
        cfg = copy.deepcopy(base_config())
        cfg['loss']['temperature'] = state.best_temperature
        cfg['loss']['bottom_k_ratio'] = state.best_bottom_k_ratio
        cfg['loss']['weight_top'] = state.best_weight_top
        cfg['loss']['weight_bottom'] = wb
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        return None
    
    best = find_best_experiment(all_r)
    wb_map = dict(wb_pairs)
    state.best_weight_bottom = wb_map.get(best['id'], 5.0)
    
    log(f"\n🏆 weight_bottom = {state.best_weight_bottom}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 4: weight_bottom 扫描", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase4: wb={state.best_weight_bottom}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase4'] = all_r
    return best


def phase5_embed_dim():
    log(f"\n{'#'*70}")
    log(f"#  Phase 5: embed_dim 扫描")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_embed_dim_sweep"
    
    ed_list = [
        ("e016", 16, [1024, 64]),
        ("e032", 32, [1024, 128]),
        ("e064", 64, [1024, 256]),
        ("e128", 128, [1024, 512]),
        ("e256", 256, [1024, 512]),
    ]
    
    all_r = []
    for eid, ed, hp in ed_list:
        cfg = copy.deepcopy(base_config())
        cfg['loss']['temperature'] = state.best_temperature
        cfg['loss']['bottom_k_ratio'] = state.best_bottom_k_ratio
        cfg['loss']['weight_top'] = state.best_weight_top
        cfg['loss']['weight_bottom'] = state.best_weight_bottom
        cfg['model']['embed_dim'] = ed
        cfg['model']['hidden_params_1'] = hp
        cfg['model']['hidden_params_2'] = hp
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        return None
    
    best = find_best_experiment(all_r)
    ed_map = {eid: (ed, hp) for eid, ed, hp in ed_list}
    state.best_embed_dim, state.best_hidden_params = ed_map.get(best['id'], (64, [1024, 256]))
    
    log(f"\n🏆 embed_dim = {state.best_embed_dim}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 5: embed_dim 扫描", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase5: ed={state.best_embed_dim}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase5'] = all_r
    return best


def phase6_pretrain_steps():
    """Phase 6: 预训练步数扫描（先跑单组学预训练，再跑 pair_pretrain）"""
    log(f"\n{'#'*70}")
    log(f"#  Phase 6: 预训练步数扫描")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_pretrain_steps_sweep"
    pretrain_base = OUTPUTS_DIR / "hca_renal_cortex_pretrain_10k"
    
    # ---- 6a: RNA 单组学预训练 ----
    log("  [6a] RNA 单组学预训练 (10000 steps)...")
    rna_cfg = {
        "task": "single_pretrain",
        "data": {
            "train_data_path": str(ROOT / "paper_figure/hca_renal_cortex/train.h5mu"),
            "test_data_path": str(ROOT / "paper_figure/hca_renal_cortex/test.h5mu"),
            "key_1": "rna_count",
            "batch_size": 256,
            "to_gpu": True,
        },
        "model": {
            "feature_num": 14577,
            "hidden_params": [1024, 256],
            "embed_dim": 64,
            "use_rmsnorm": True,
            "use_residual": True,
            "dropout_p": 0.0,
        },
        "training": {
            "project_dir": str(pretrain_base / "rna_pretrain"),
            "train_steps": 10000,
            "eval_points": 500,
            "save_points": 2000,
            "device": "cuda",
        },
        "optimizer": {
            "lr": 1e-3,
            "warmup_steps": 400,
            "steady_1_steps": 0,
            "cosine_anneal_steps": 9600,
            "min_lr": 1e-4,
        },
        "loss": {"vae_beta": 1.0},
    }
    
    rna_cn = "hca_renal_cortex_single_pretrain_rna"
    write_yaml(rna_cfg, CONFIGS_DIR / f"{rna_cn}.yaml")
    
    cmd = f"source {CONDA_SH} && conda activate snapatac && bash scripts/train.sh {CONFIGS_DIR / f'{rna_cn}.yaml'} cuda"
    ok = run_cmd(cmd, log_file=LOGS_DIR / f"ablation_train_{rna_cn}.out")
    if not ok:
        log("  ⚠️ RNA 预训练失败，跳过 Phase 6")
        return None
    log("  ✅ RNA 预训练完成")
    
    # ---- 6a: ATAC 单组学预训练 ----
    log("  [6a] ATAC 单组学预训练 (10000 steps)...")
    atac_cfg = copy.deepcopy(rna_cfg)
    atac_cfg['data']['key_1'] = "peak_count"
    atac_cfg['model']['feature_num'] = 101123
    atac_cfg['training']['project_dir'] = str(pretrain_base / "atac_pretrain")
    
    atac_cn = "hca_renal_cortex_single_pretrain_atac"
    write_yaml(atac_cfg, CONFIGS_DIR / f"{atac_cn}.yaml")
    
    cmd = f"source {CONDA_SH} && conda activate snapatac && bash scripts/train.sh {CONFIGS_DIR / f'{atac_cn}.yaml'} cuda"
    ok = run_cmd(cmd, log_file=LOGS_DIR / f"ablation_train_{atac_cn}.out")
    if not ok:
        log("  ⚠️ ATAC 预训练失败，跳过 Phase 6")
        return None
    log("  ✅ ATAC 预训练完成")
    
    # ---- 6b: pair_pretrain with different checkpoints ----
    log("  [6b] 不同预训练步数 pair_pretrain...")
    
    ckpt_steps = [2000, 4000, 6000, 8000, 10000]
    pt_names = ["pt2k", "pt4k", "pt6k", "pt8k", "pt10k"]
    
    all_r = []
    for eid, cs in zip(pt_names, ckpt_steps):
        cfg = copy.deepcopy(base_config())
        cfg['loss']['temperature'] = state.best_temperature
        cfg['loss']['bottom_k_ratio'] = state.best_bottom_k_ratio
        cfg['loss']['weight_top'] = state.best_weight_top
        cfg['loss']['weight_bottom'] = state.best_weight_bottom
        cfg['model']['embed_dim'] = state.best_embed_dim or 64
        cfg['model']['hidden_params_1'] = state.best_hidden_params or [1024, 256]
        cfg['model']['hidden_params_2'] = state.best_hidden_params or [1024, 256]
        cfg['ckpt']['omic_1'] = str(pretrain_base / "rna_pretrain" / "models" / f"ckpt_{cs}.pth")
        cfg['ckpt']['omic_2'] = str(pretrain_base / "atac_pretrain" / "models" / f"ckpt_{cs}.pth")
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        return None
    
    best = find_best_experiment(all_r)
    pt_map = dict(zip(pt_names, ckpt_steps))
    state.best_pretrain_steps = pt_map.get(best['id'], 4000)
    
    log(f"\n🏆 pretrain_steps = {state.best_pretrain_steps}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 6: 预训练步数扫描", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase6: pt={state.best_pretrain_steps}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase6'] = all_r
    return best


def phase7_loss_weights():
    log(f"\n{'#'*70}")
    log(f"#  Phase 7: Loss 权重调整")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_loss_weights_sweep"
    
    all_r = []
    
    # clip_weight 扫描（cross_recon=0.75 固定）
    for eid, cw, cr in [("lw_clip10", 10.0, 0.75), ("lw_clip20", 20.0, 0.75), ("lw_clip40", 40.0, 0.75)]:
        cfg = _build_best_config()
        cfg['loss']['clip_weight'] = cw
        cfg['loss']['cross_recon_1'] = cr
        cfg['loss']['cross_recon_2'] = cr
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    # 确定最优 clip_weight
    clip_r = [r for r in all_r if 'clip' in r['id']]
    if clip_r:
        best_clip = find_best_experiment(clip_r)
        state.best_clip_weight = 10.0 if best_clip['id'] == 'lw_clip10' else (40.0 if best_clip['id'] == 'lw_clip40' else 20.0)
    else:
        state.best_clip_weight = 20.0
    
    # cross_recon 扫描（clip_weight=最优）
    for eid, cw, cr in [("lw_cr05", state.best_clip_weight, 0.50), ("lw_cr10", state.best_clip_weight, 1.00)]:
        cfg = _build_best_config()
        cfg['loss']['clip_weight'] = cw
        cfg['loss']['cross_recon_1'] = cr
        cfg['loss']['cross_recon_2'] = cr
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        return None
    
    best = find_best_experiment(all_r)
    log(f"\n🏆 clip_weight={state.best_clip_weight}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 7: Loss 权重调整", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase7: cw={state.best_clip_weight}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase7'] = all_r
    return best


def phase8_batch_size():
    log(f"\n{'#'*70}")
    log(f"#  Phase 8: Batch Size 扫描")
    log(f"{'#'*70}")
    
    phase_dir = "2026-07-23_batch_size_sweep"
    
    bs_list = [
        ("bs128", 128, 24000, 2000),
        ("bs256", 256, 12000, 1000),
        ("bs512", 512, 6000, 500),
        ("bs1024", 1024, 3000, 250),
    ]
    
    all_r = []
    for eid, bs, steps, save_pts in bs_list:
        cfg = _build_best_config()
        cfg['data']['batch_size'] = bs
        cfg['training']['train_steps'] = steps
        cfg['training']['save_points'] = save_pts
        cfg['training']['project_dir'] = f"outputs/hca_renal_cortex_{eid}"
        
        cn = f"hca_renal_cortex_{eid}"
        write_yaml(cfg, CONFIGS_DIR / f"{cn}.yaml")
        
        r = run_experiment(cn, f"hca_renal_cortex_{eid}", eid, phase_dir)
        if r:
            all_r.append(r)
    
    if not all_r:
        return None
    
    best = find_best_experiment(all_r)
    bs_map = {eid: bv for eid, bv, _, _ in bs_list}
    state.best_batch_size = bs_map.get(best['id'], 512)
    
    log(f"\n🏆 batch_size = {state.best_batch_size}, top_1={best['top_1']:.6f}")
    
    generate_summary_md("Phase 8: Batch Size 扫描", all_r, best['id'], phase_dir)
    git_commit_push(phase_dir, f"[exp] Phase8: bs={state.best_batch_size}, top_1={best['top_1']:.6f}")
    
    state.all_results['phase8'] = all_r
    return best


def _build_best_config():
    """构建包含当前所有最优参数的配置"""
    cfg = copy.deepcopy(base_config())
    for attr, loss_key in [
        ('best_temperature', 'temperature'),
        ('best_bottom_k_ratio', 'bottom_k_ratio'),
        ('best_weight_top', 'weight_top'),
        ('best_weight_bottom', 'weight_bottom'),
    ]:
        val = getattr(state, attr)
        if val is not None:
            cfg['loss'][loss_key] = val
    if state.best_embed_dim is not None:
        cfg['model']['embed_dim'] = state.best_embed_dim
    if state.best_hidden_params is not None:
        cfg['model']['hidden_params_1'] = state.best_hidden_params
        cfg['model']['hidden_params_2'] = state.best_hidden_params
    if state.best_clip_weight is not None:
        cfg['loss']['clip_weight'] = state.best_clip_weight
    return cfg


def generate_final_summary():
    """最终汇总报告"""
    log(f"\n{'#'*70}")
    log(f"#  最终汇总报告")
    log(f"{'#'*70}")
    
    lines = [
        "# HCA Renal Cortex 消融实验 - 最终汇总",
        "",
        f"生成时间: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 全链路最优配置",
        "",
        "| 阶段 | 参数 | 最优值 | top_1 |",
        "|------|------|--------|------:|",
    ]
    
    phase_info = [
        ("Phase 1", "temperature", state.best_temperature),
        ("Phase 2", "bottom_k_ratio", state.best_bottom_k_ratio),
        ("Phase 3", "weight_top", state.best_weight_top),
        ("Phase 4", "weight_bottom", state.best_weight_bottom),
        ("Phase 5", "embed_dim", state.best_embed_dim),
        ("Phase 6", "pretrain_steps", state.best_pretrain_steps),
        ("Phase 7", "clip_weight", state.best_clip_weight),
        ("Phase 8", "batch_size", state.best_batch_size),
    ]
    
    phase_keys = ['phase1','phase2','phase3','phase4','phase5','phase6','phase7','phase8']
    
    for (ph, param, val), pk in zip(phase_info, phase_keys):
        if val is not None:
            results = state.all_results.get(pk, [])
            bt1 = max(r['top_1'] for r in results) if results else None
            lines.append(f"| {ph} | {param} | {val} | {bt1:.6f} |" if bt1 else f"| {ph} | {param} | {val} | N/A |")
    
    lines.append("")
    lines.append("## 各阶段 top_1_hit 增益")
    lines.append("")
    lines.append("| 阶段 | 进入基线 top_1 | 阶段最优 top_1 | top_1 Δ | foscttm Δ |")
    lines.append("|------|---------------:|---------------:|--------:|----------:|")
    
    baseline_top1 = 0.013115  # t030
    prev_t1, prev_fos = baseline_top1, None
    
    for pk, pn in zip(phase_keys, phase_info):
        ph, _, _ = pn
        results = state.all_results.get(pk, [])
        if results:
            best = max(results, key=lambda x: x['top_1'])
            dt = best['top_1'] - prev_t1
            df = best['foscttm'] - prev_fos if prev_fos is not None else 0
            lines.append(f"| {ph} | {prev_t1:.6f} | {best['top_1']:.6f} | {dt:+.6f} | {df:+.6f} |")
            prev_t1, prev_fos = best['top_1'], best['foscttm']
    
    lines.append("")
    lines.append("## 与 MultiVI 对比")
    lines.append("")
    lines.append(f"- MultiVI top_1: 0.01418")
    lines.append(f"- 消融最终 top_1: {prev_t1:.6f}")
    lines.append(f"- 差距: {prev_t1 - 0.01418:+.6f}")
    lines.append("")
    
    content = '\n'.join(lines)
    fp = EXP_REPORTS_DIR / "final_summary.md"
    with open(fp, 'w') as f:
        f.write(content)
    log(f"  📊 最终报告 → {fp}")
    
    git_commit_push(".", f"[exp] Final: all phases done, top_1={prev_t1:.6f}")
    
    return content


# ============ 主函数 ============

def main():
    log("="*70)
    log("  HCA Renal Cortex 消融实验自动编排")
    log(f"  开始: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log("="*70)
    
    # 环境检查
    log("检查环境...")
    ok = run_cmd(
        f"source {CONDA_SH} && conda activate snapatac && python -c 'import torch; assert torch.cuda.is_available(); print(\"OK\")'"
    )
    if not ok:
        log("❌ 环境不可用")
        sys.exit(1)
    log("✅ 环境就绪\n")
    
    try:
        # Phase 1: Temperature（包含已有 t007-t030，新增 t040/t050/t070/t100）
        phase1_temperature()
        
        # Phase 2: bottom_k_ratio
        phase2_bottom_k()
        
        # Phase 3: weight_top
        phase3_weight_top()
        
        # Phase 4: weight_bottom
        phase4_weight_bottom()
        
        # Phase 5: embed_dim
        phase5_embed_dim()
        
        # Phase 6: 预训练步数（跳过 - 需要 HuggingFace dataset 格式，h5mu 不兼容）
        log("\n⚠️  Phase 6 预训练步数扫描跳过（CLI single_pretrain 需要 dataset_path，非 h5mu 格式）")
        # phase6_pretrain_steps()
        
        # Phase 7: Loss 权重
        phase7_loss_weights()
        
        # Phase 8: Batch Size
        phase8_batch_size()
        
        # 最终汇总
        generate_final_summary()
        
    except KeyboardInterrupt:
        log("\n⚠️ 用户中断")
    except Exception as e:
        log(f"\n❌ 异常: {e}")
        import traceback
        traceback.print_exc()
    
    log(f"\n{'='*70}")
    log(f"  结束: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log(f"{'='*70}")


if __name__ == "__main__":
    main()
